name: plantvision_mobile
description: Industrial Photo Repository Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.2.0
  
  # Local Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # HTTP & API
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Camera & Media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Authentication
  local_auth: ^2.1.7
  jwt_decoder: ^2.0.1
  
  # Background Services
  workmanager: ^0.5.1
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  
  # QR/Barcode Scanner
  mobile_scanner: ^3.5.5
  
  # Network Info
  connectivity_plus: ^5.0.1
  
  # Permissions
  permission_handler: ^11.0.1
  
  # UI Components
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  
  # Utils
  uuid: ^4.1.0
  logger: ^2.0.2+1
  
  # Cupertino Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
